version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://user:pass@db:5432/real_book
    ports:
      - 8080:8080

  db:
    image: postgres:11.9-alpine
    environment:
      POSTGRES_DB: real_book
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
